### ISSUE TITLE
Recently added TypeScript definition breaks ES6 imports

### ISSUE THREAD

**Issue by jameswilddev** [sindresorhus/tempfile#11]
Hello!

I have a project which uses `tempfile` as an ES6 import in TypeScript, importing as follows:

`import * as tempfile from "tempfile"`

This used to work, but as of the latest version, I instead see:

`This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export`

I can't turn this on as it breaks other things.

The definition looks similar to what was already in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/tempfile so I'm not sure what caused this exactly.

Thanks.

**Comment by sindresorhus** [comment]
This package now ships with its own type definition. It might not be exactly like the one on DefinitelyTyped. You need to import it as:

```
import tempfile = require('tempfile');
```

**Comment by jameswilddev** [comment]
I hadn't seen that particular import syntax before; thanks, that seems to fix it and might mean I can use type definitions for other modules.
