### ISSUE TITLE
POSIX $TMPDIR environment should be taken in account

### ISSUE THREAD

**Issue by kelson42** [sindresorhus/tempfile#12]
This modules seems to always, per default, create a path in `/tmp` directory. Unfortunately this is not only the right temporary directory path. If `$TMPDIR` is set this should be taken in account.

**Comment by sindresorhus** [comment]
We use the Node.js `os.tmpdir()` method, which does take it into account: https://github.com/nodejs/node/blob/233cdb64a95eaabce922d773f3e312565e18a9d4/lib/os.js#L124-L143

**Comment by kelson42** [comment]
Indeed. After investigating it seems that my problem is that it is make at import time and not at runtime.
