### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by abhimanyuPatil** [sindresorhus/tempfile#15]
Hi,
I've installed tempfile in my Node, Express, Typescript project. But I am getting while importing it.
Error is as follows
`require() of ES Module /Users/chanondler/Desktop/repos/mirage-api-v2/node_modules/tempfile/index.js from /Users/chanondler/Desktop/repos/mirage-api-v2/dist/src/controllers/lead.controller.js not supported.\nInstead change the require of index.js in /Users/chanondler/Desktop/repos/mirage-api-v2/dist/src/controllers/lead.controller.js to a dynamic import() which is available in all CommonJS modules."`

Tried 

- `import tempfile from "tempfile";`
- `let tempfile = require('tempfile')`
- `let tempfile: any;
import("tempfile").then((res) => (tempfile = res.default));
`

But none of the above work
System and App configuration
`Nodejs v17.4.0`
`Express v4.16`
`Tempfile v4.0.0`
`Macbook air M1`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
