### ISSUE TITLE
Why is tempy better?

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/tempfile#16]
Hi! Someone on my team started using `tempfile` (this library) and it works fine. Is there a risk/what's the reason we should switch to `tempy`?

**Comment by sindresorhus** [comment]
`tempy` is better in that it has more options and the ability to also clean up the temporary file and directory. It's fine to use `tempfile` if you have simple needs. `tempfile` is not deprecated. It's just that I feel `tempy` is better.
